
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://heboayvlgqyagsytbqss.supabase.co";
// Fixed Supabase key with longer expiration
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlYm9heXZsZ3F5YWdzeXRicXNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMDQ5OTksImV4cCI6MjA1OTY4MDk5OX0.zcunxn_wZJwcXHbu-zB1mcqOmzwhPLj7SRstgiRWVKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: (url, options) => {
      console.log("Supabase fetch:", url);
      return fetch(url, options);
    }
  }
});

// Add debug logging to track Supabase connectivity issues
supabase.auth.onAuthStateChange((event, session) => {
  console.log("Supabase auth event:", event, "Session:", session ? "Active" : "None");
});
